steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_NAME}/${_IMAGE_NAME}:$COMMIT_SHA'
      - '-t'
      - '${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_NAME}/${_IMAGE_NAME}:latest'
      - '.'

  # Push the image with the commit SHA tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_NAME}/${_IMAGE_NAME}:$COMMIT_SHA'

  # Push the image with the latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_NAME}/${_IMAGE_NAME}:latest'

images:
  - '${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_NAME}/${_IMAGE_NAME}:$COMMIT_SHA'
  - '${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_NAME}/${_IMAGE_NAME}:latest'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _AR_REGION: 'us-east5'
  _AR_REPO_NAME: 'builders'
  _IMAGE_NAME: 'google-cloud-cli'
