steps:
  # Set up QEMU for multi-architecture builds
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', '--rm', '--privileged', 'multiarch/qemu-user-static', '--reset', '-p', 'yes']

  # Create and use a new buildx builder
  - name: 'gcr.io/cloud-builders/docker'
    args: ['buildx', 'create', '--name', 'mybuilder', '--driver', 'docker-container', '--use']

  # Build the container image for both amd64 and arm64 architectures
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'buildx'
      - 'build'
      - '--platform'
      - 'linux/amd64,linux/arm64'
      - '-t'
      - '${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_NAME}/${_IMAGE_NAME}:$COMMIT_SHA'
      - '-t'
      - '${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_NAME}/${_IMAGE_NAME}:latest'
      - '-f'
      - 'Dockerfile'
      - '--push'
      - 'ctx'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _AR_REGION: 'us-east5'
  _AR_REPO_NAME: 'builders'
  _IMAGE_NAME: 'google-cloud-cli'
